# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Hygon Information Technology Co., Ltd.

apiVersion: v2
name: hcu-label-node
description: A Helm chart for HCU label node
type: application
version: 3.0.0
appVersion: v3.0.0
