# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Hygon Information Technology Co., Ltd.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default "kube-system" }}
spec:
  {{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}-cntr
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: {{ .Values.privileged }}
        command: [ "./hcu-label-node" ]
        args:
          {{- if .Values.labels.name }}
          - "-name"
          {{- end }}
          {{- if .Values.labels.cuCount }}
          - "-cu-count"
          {{- end }}
          {{- if .Values.labels.vram }}
          - "-vram"
          {{- end }}
          {{- if .Values.labels.driverVersion }}
          - "-driver-version"
          {{- end }}
          - "-logtostderr={{ .Values.log.logtostderr }}"
          - "-stderrthreshold={{ .Values.log.stderrthreshold }}"
          - "-v={{ .Values.log.verbosity }}"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
          - name: dev
            mountPath: /dev
          - name: local
            mountPath: /usr/local
          - name: opt
            mountPath: /opt
            readOnly: true
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: local
          hostPath:
            path: /usr/local
        - name: opt
          hostPath:
            path: /opt
